### ISSUE TITLE
Main.css File is missing

### ISSUE THREAD

**Issue by ur2l84me** [vad-ii-k/Digital-Planner#3]
hey, 
i love what you did here. 
I am trying to understand how you did it and I have trouble running the program and generating an output similar to yours. 
I think the reason is that you are referencing a main.css file which is not included in the directory. 

( Line 55 in planner_generator.py  await generate_pdf('./dist/index.html', './dist/main.css', './dist/planner.pdf') )

I tried running it with ./docs/dist/css.style.css but I do not get a file that looks even remotely similar to yours. 

Any chance you are willing to share your main.css file?

**Comment by vad-ii-k** [comment]
Hi, thanks for the feedback!

I just added the instruction to the README. After calling the `npm build` command, the main.css file will appear in the dist directory.

I hope it helped) Good luck!
